import React from 'react'
import Head from 'next/head'

function Form() {
  return (
    <div className='text-white h-full sm:h-screen sm:overflow-hidden bg-center bg-cover custom-img'>
      <Head>
          <title>Finn van de Wiel - Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon/favicon.ico" />
        </Head>
      <div className='max-w-[1240px] m-auto px-2 py-16 w-full'>
        <h2 className='py-4 flex justify-center text-xl font-bold'>Get In Touch With Me</h2>
        <div className='grid lg:grid-cols-5 gap-8'>
          <div className='col-span-5 w-full h-auto  rounded-xl lg:p-4'>
            <div className='p-4'>
              <form>
                <div className='grid md:grid-cols-2 gap-4 w-full py-2'>
                  <div className='flex flex-col'>
                    <label className='uppercase text-sm py-2'>Name</label>
                    <input
                      className='opacity-80 border-2 rounded-lg p-3 flex border-gray-300'
                      type='text'
                      name='name'
                    />
                  </div>
                  <div className='flex flex-col'>
                    <label className='uppercase text-sm py-2'>
                      Phone Number
                    </label>
                    <input
                      className='opacity-80 border-2 rounded-lg p-3 flex border-gray-300'
                      type='text'
                      name='phone'
                    />
                  </div>
                </div>
                <div className='flex flex-col py-2'>
                  <label className='uppercase text-sm py-2'>Email</label>
                  <input
                    className='opacity-80 border-2 rounded-lg p-3 flex border-gray-300'
                    type='email'
                    name='email'
                  />
                </div>
                <div className='flex flex-col py-2'>
                  <label className='uppercase text-sm py-2'>Subject</label>
                  <input
                    className='opacity-80 border-2 rounded-lg p-3 flex border-gray-300'
                    type='text'
                    name='subject'
                  />
                </div>
                <div className='flex flex-col py-2'>
                  <label className='uppercase text-sm py-2'>Message</label>
                  <textarea
                    className='opacity-80 border-2 rounded-lg p-3 border-gray-300'
                    rows='10'
                    name='message'
                  ></textarea>
                </div>
                <button className='px-8 py-4 mt-4 border w-full rounded-lg'>
                  Send Message
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Form
