import React from 'react'
import Head from 'next/head'
import Hero from '../components/Hero'
import Project from '../components/Project'
import { SiTailwindcss, SiNextdotjs, SiFirebase } from 'react-icons/si'
import { DiJsBadge, DiHtml5, DiCss3, DiReact } from 'react-icons/di'

const work = () => {
  return (
    <div>
        <Head>
          <title>Finn van de Wiel - Projects</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon/favicon.ico" />
        </Head>
        <Hero heading='My Work' message='Some things I made.' link='/contact' linkcontent="Contact" />
        <div className='flex justify-center'>
            <h1 className='font-bold text-2xl sm:text-4xl mt-10 mb-20'>This is some of my Work!</h1>
        </div>
        <Project ProjectTitle='AvansQuesions' 
              ProjectText='This is a web-app where you can ask questions and other people can awnser them. The website has authentication made with firebase and you can login using your Google account. The application was built using Next.js and Tailwind. Tge website itself is hosted on Vercel via the github repository. You can try the application yourself and even add your own questions! Maybe someone else will awnser them for you!' 
              ProjectImg="aq3.png"
              ProjectGithub="https://github.com/FinnWiel/SchoolQuestions"
              ProjectLink="https://school-questions-1dha.vercel.app/"
              ProjectIcon1={ <SiTailwindcss size={30}/> }
              ProjectIcon2={ <SiNextdotjs size={30} />} 
              ProjectIcon3={ <SiFirebase size={30} />}
              />
        <Project ProjectTitle='Movie App'
              ProjectText='This is a Movie App usng an API to lookup movies in the database. You ccan search via title and it will show all the movies in that database to you on the displayed cards. When you hover over the cards it displays some additional information about the movie or series!' 
              ProjectImg="garf.png"
              ProjectGithub="/"
              ProjectLink="/"
              ProjectIcon1={<DiReact size={35} />}
              ProjectIcon3={ <DiCss3 size={30}/> }
              />
        <Project ProjectTitle='Todo'
              ProjectText='This is a TODO app I made using HTML CSS and JavaScript. You can make a TODO-item and it will store it in your broweser so when you refresh the page it is still there. You can log 2 different types of TODOs, work and personal. Make your own todo list and organize all of your tasks!' 
              ProjectImg="td.png"
              ProjectGithub="/"
              ProjectLink="/"
              ProjectIcon1={ <DiJsBadge size={30}/> }
              ProjectIcon2={ <DiHtml5 size={30}/> }
              ProjectIcon3={ <DiCss3 size={30}/> }
              />
        <Project ProjectTitle='About me'
              ProjectText='This is a simple website I made for a school project.' 
              ProjectImg="adwe.png"
              ProjectGithub="/"
              ProjectLink="https://adwe.vercel.app/#"
              ProjectIcon1={ <DiJsBadge size={30}/> }
              ProjectIcon2={ <DiHtml5 size={30}/> }
              ProjectIcon3={ <DiCss3 size={30}/> }
              />
        
    </div>
  )
}

export default work