import React from 'react'
import Head from 'next/head'
import Hero from '../components/Hero'
import Project from '../components/Project'
import { SiTailwindcss, SiNextdotjs, SiFirebase } from 'react-icons/si'
import { DiJsBadge, DiHtml5, DiCss3 } from 'react-icons/di'

const work = () => {
  return (
    <div>
        <Head>
          <title>Finn van de Wiel - Projects</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon/favicon.ico" />
        </Head>
        <Hero heading='My Work' message='Some things I made.' link='/contact' linkcontent="Contact" />
        <div className='flex justify-center'>
            <h1 className='font-bold text-2xl sm:text-4xl mt-10 mb-20'>This is some of my Work!</h1>
        </div>
        <Project ProjectTitle='AvansQuesions' 
              ProjectText='This is a web-app where you can ask questions and other people can awnser them. The website has authentication made with firebase and you can login using your Google account. The application was built using Next.js and Tailwind. Tge website itself is hosted on Vercel via the github repository. You can try the application yourself and even add your own questions! Maybe someone else will awnser them for you!' 
              ProjectImg="aq3.png"
              ProjectGithub="https://github.com/FinnWiel/SchoolQuestions"
              ProjectLink="https://school-questions-1dha.vercel.app/"
              ProjectIcon1={ <SiTailwindcss size={30}/> }
              ProjectIcon2={ <SiNextdotjs size={30} />} 
              ProjectIcon3={ <SiFirebase size={30} />}
              />
        <Project ProjectTitle='Todo List'
              ProjectText='This is a TODO app I made using HTML CSS and JavaScript. You can make a TODO-item and it will store it in your broweser so when you refresh the page it is still there. You can log 2 different types of TODOs, work and personal. Make your own todo list and organize all of your tasks!' 
              ProjectImg="td.png"
              ProjectGithub="/"
              ProjectLink="/"
              ProjectIcon1={ <DiJsBadge size={30}/> }
              ProjectIcon2={ <DiHtml5 size={30}/> }
              ProjectIcon3={ <DiCss3 size={30}/> }
              />
    </div>
  )
}

export default work